name: Bridge Transfer Video to Player4Me

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Link m3u8 dari LK21'
        required: true
        default: 'https://edge1-madrid-sprintcdn.r66nv9ed.com/hls2/02/02722/wqzadn6kl63z_h/index-v1-a1.m3u8?t=AhjP_qDhvXpSkzk6wIN9fHmWVn1jxb0Tbdd9SJJKBXA&s=1778632664&e=10800&f=13739365&srv=1055&asn=140478&sp=4000&p=0'
      ftp_host:
        description: 'FTP Host (dari Player4Me)'
        required: true
      ftp_user:
        description: 'FTP Username'
        required: true
      ftp_pass:
        description: 'FTP Password'
        required: true

jobs:
  transfer_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          pip install yt-dlp

      - name: Download Video ke GitHub
        run: |
          echo "Memulai download dari link sumber..."
          yt-dlp "${{ github.event.inputs.video_url }}" -o "film_movie.mp4"

      - name: Upload ke Player4Me via FTP
        run: |
          echo "Mengirim file ke Player4Me..."
          lftp -e "set ftp:ssl-allow no; put -O / film_movie.mp4; quit" \
               -u "${{ github.event.inputs.ftp_user }},${{ github.event.inputs.ftp_pass }}" \
               "${{ github.event.inputs.ftp_host }}"
